on:
    release:
        types:
          - published

name: Push to game template

jobs:
    game-template:
        uses: deep-entertainment/egoventure-game-template/.github/workflows/game-template.yaml@main
        with:
            addon: speedy_gonzales
            branch: "main"
        secrets:
            token: "{{ secrets.DEPLOYMENT_TOKEN }}"
