on:
    release:
        types:
          - published

name: Push to game template

jobs:
    game-template:
        if: github.event.action == 'released'
        uses: deep-entertainment/egoventure-game-template/.github/workflows/game-template.yml@main
        with:
            addon: speedy_gonzales
            branch: "${{ env.branch }}"
