on:
    release:
        types:
          - published

name: Push to game template

env:
    BRANCH: "${{ fromJson('{ \"prereleased\": \"develop\", \"released\": \"main\" }')[github.event.action] }}"

jobs:
    game-template:
        uses: deep-entertainment/egoventure-game-template/.github/workflows/game-template.yaml@main
            with:
                addon: speedy_gonzales
                branch: "${{ env.branch }}"
