name: "Release new version"

on:
    push:
        branches:
            - develop
            - main

jobs:
    release-dev:
        uses: deep-entertainment/egoventure-example-game/.github/workflows/release.shared.yml@develop
        if: github.ref_name == "develop"
    release-main:
        uses: deep-entertainment/egoventure-example-game/.github/workflows/release.shared.yml@main
        if: github.ref_name == "main"

