name: "Release new version"

on:
    push:
        branches:
            - develop

jobs:
    release-dev:
        uses: deep-entertainment/egoventure-example-game/.github/workflows/release.shared.yml@develop
