name: "Release new version"

on:
    push:
        branches:
            - develop
            - main

jobs:
    release:
        uses: deep-entertainment/egoventure-example-game/.github/workflows/release.shared.yml@${{ github.ref_name }}
